name: Build and Deploy Resume

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache texlive Docker image
        uses: actions/cache@v3
        id: docker-cache
        with:
          path: /tmp/texlive-docker.tar
          key: texlive-full-2025 # bump this string if you want a fresh pull

      - name: Load cached Docker image
        if: steps.docker-cache.outputs.cache-hit == 'true'
        run: docker load -i /tmp/texlive-docker.tar

      - name: Pull and save Docker image
        if: steps.docker-cache.outputs.cache-hit != 'true'
        run: |
          docker pull ghcr.io/xu-cheng/texlive-full:latest
          docker save ghcr.io/xu-cheng/texlive-full:latest -o /tmp/texlive-docker.tar

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          latexmk_use_lualatex: true

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: "."
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
