name: Keep Cache Alive

on:
  schedule:
    - cron: "0 0 */5 * *" # every 5 days

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Docker cache
        uses: actions/cache@v3
        with:
          path: /tmp/texlive-docker.tar
          key: texlive-full-2025
